In [23]:
import numpy as np
a = np.array([[1,6],[2,8],[3,11],[3,10],[1,7]])  #задание1#
print(a)
c = a[0:,0].copy()
d = a[0:,1].copy()
print(c)
print(d)
c_mean = np.mean(c)
d_mean = np.mean(d)
print(c_mean)
print(d_mean)
mean_a = np.array([c_mean,d_mean])
print(mean_a)
a_centred = a - mean_a        #задание 2#
print(a_centred)
a_centred_st1 = a_centred[0:,0].copy()
a_centred_st2 = a_centred[0:,1].copy()
a_centred_sp = np.dot(a_centred_st1,a_centred_st2)
print(a_centred_sp)
a_c_sp_div = a_centred_sp/4
print(a_c_sp_div)


[[ 1  6]
 [ 2  8]
 [ 3 11]
 [ 3 10]
 [ 1  7]]
[1 2 3 3 1]
[ 6  8 11 10  7]
2.0
8.4
[2.  8.4]
[[-1.  -2.4]
 [ 0.  -0.4]
 [ 1.   2.6]
 [ 1.   1.6]
 [-1.  -1.4]]
8.0
2.0
